# OJS Persistent Volume Claims
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ojs-files-pvc
  labels:
    app: ojs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ojs-public-pvc
  labels:
    app: ojs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ojs-mysql-pvc
  labels:
    app: ojs-mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
